automation:
  - alias: BlissLight3 (Wind)
    description: "Wind Light That Changes Based on Brightness"
    trigger: 
      - platform: time_pattern
        seconds: "/10"
    action: 
      - service: light.turn_on
        target:
          entity_id: light.blissember3
        data:
          brightness: >
            {% set pct = states('sensor.wind_generation') | float(0) %}
            {% set brightness = ((pct / 100) * 254) + 1 %}
            {{ brightness | round(0) | int }}
          hs_color: [120, 100] 
    mode: single 