sensor:
  - platform: rest
    resource: "https://JSONwebfileaddresshere"
    name: LGEJSONReadFile
    scan_interval: 20
  
    value_template: '1'
    json_attributes:
      - "Time"
      - "Wind Generation (kW)"
      - "Solar Generation (kW)"
      - "Solar Generation (%)"
      - "Wind Generation (%)"     
      - "Hydro Generation (%)"  
   
    authentication: basic
